"""Initial migration

Revision ID: 1032ba3b8a87
Revises: 
Create Date: 2025-08-24 11:52:44.627343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1032ba3b8a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('portfolios',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('color_theme', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_name'), ['name'], unique=True)

    op.create_table('years',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='fk_department_portfolio', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'portfolio_id', name='uq_department_name_portfolio')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('subsidiaries',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('cluster', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_subsidiary_department', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='fk_subsidiary_portfolio', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subsidiaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subsidiaries_cluster'), ['cluster'], unique=False)
        batch_op.create_index(batch_op.f('ix_subsidiaries_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subsidiaries_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_subsidiaries_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subsidiaries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_subsidiaries_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name='fk_category_parent', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name='fk_category_subsidiary', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_category_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_attribute_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpis',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('target IS NULL OR target BETWEEN 0 AND 100', name='chk_kpi_target_range'),
    sa.CheckConstraint('weight > 0', name='chk_kpi_positive_weight'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='fk_kpi_attribute', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_kpi_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpis_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpis_category_id'), ['category_id'], unique=False)

    op.create_table('scores',
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actual IS NULL OR actual >= 0', name='chk_score_actual_positive'),
    sa.CheckConstraint('target IS NULL OR target >= 0', name='chk_score_target_positive'),
    sa.CheckConstraint('weight IS NULL OR weight >= 0', name='chk_score_weight_positive'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='fk_score_attribute', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name='fk_score_subsidiary', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_score_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subsidiary_id', 'year_id', 'attribute_id', name='uq_score_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpis_category_id'))
        batch_op.drop_index(batch_op.f('ix_kpis_attribute_id'))

    op.drop_table('kpis')
    op.drop_table('attributes')
    op.drop_table('categories')
    with op.batch_alter_table('subsidiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subsidiaries_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_subsidiaries_name'))
        batch_op.drop_index(batch_op.f('ix_subsidiaries_is_active'))
        batch_op.drop_index(batch_op.f('ix_subsidiaries_industry'))
        batch_op.drop_index(batch_op.f('ix_subsidiaries_department_id'))
        batch_op.drop_index(batch_op.f('ix_subsidiaries_cluster'))

    op.drop_table('subsidiaries')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_departments_name'))

    op.drop_table('departments')
    op.drop_table('years')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_name'))
        batch_op.drop_index(batch_op.f('ix_portfolios_is_active'))

    op.drop_table('portfolios')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_is_active'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
